# .github/workflows/auto-rerun.yml
name: Auto Rerun Daily Derper Build (on failure)

on:
  workflow_run:
    workflows: ["Daily Derper Build"]   # 监听 A
    types: [completed]

permissions:
  actions: write
  contents: read

jobs:
  rerun-on-failure:
    # 失败才重试；最多尝试 3 次（首次 + 2 次重试）
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 3 }}
    runs-on: ubuntu-24.04
    steps:
      - name: Re-run the entire workflow run
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # gh CLI 读取 GH_TOKEN
        run: |
          echo "Previous run attempt: ${{ github.event.workflow_run.run_attempt }}"
          gh api -X POST repos/${{ github.repository }}/actions/runs/${RUN_ID}/rerun
